#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-representable
Version  : 2.2.3
Release  : 2
URL      : https://rubygems.org/downloads/representable-2.2.3.gem
Source0  : https://rubygems.org/downloads/representable-2.2.3.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-bundler
BuildRequires : rubygem-json
BuildRequires : rubygem-mini_portile
BuildRequires : rubygem-minitest
BuildRequires : rubygem-mongoid
BuildRequires : rubygem-multi_json
BuildRequires : rubygem-nokogiri
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-ruby-prof
BuildRequires : rubygem-test_xml
BuildRequires : rubygem-uber
BuildRequires : rubygem-virtus

%description
# Representable
Representable maps Ruby objects to documents and back.
In other words: Take an object and decorate it with a representer module. This will allow you to render a JSON, XML or YAML document from that object. But that's only half of it! You can also use representers to parse a document and create or populate an object.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n representable-2.2.3
gem spec %{SOURCE0} -l --ruby > rubygem-representable.gemspec

%build
gem build rubygem-representable.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
representable-2.2.3.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/representable-2.2.3
ruby -v -I.:lib:test test*/test_*.rb
ruby -v -I.:lib:test test*/*_test.rb
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/representable-2.2.3.gem
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Apply/apply-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Apply/cdesc-Apply.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/Collection/cdesc-Collection.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/Collection/deserializer_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/Collection/populator_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/Collection/serializer_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/Collection/skipable_empty_value%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/Factories/cdesc-Factories.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/Factories/deserializer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/Factories/deserializer_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/Factories/populator-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/Factories/populator_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/Factories/serializer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/Factories/serializer_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/FragmentNotFound/cdesc-FragmentNotFound.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/Hash/cdesc-Hash.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/Hash/deserializer_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/Hash/populator_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/Hash/serializer_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/array%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/array-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/as-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/build-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/cached_representer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/cdesc-Binding.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/compile_fragment-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/default_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/evaluate_option-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/exec_context-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/get-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/getter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/has_default%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/has_default-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/parent_decorator-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/parse_filter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/read_fragment-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/render_filter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/render_fragment-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/representable%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/representable-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/represented-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/representer_module_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/serialize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/set-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/setter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/setup_exec_context%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/skip_filters%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/skip_filters-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/skipable_empty_value%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/typed%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/typed-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/uncompile_fragment-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/update%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/user_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Binding/write_fragment-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Cached/Binding/cdesc-Binding.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Cached/Binding/deserializer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Cached/Binding/serializer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Cached/Serializer/cdesc-Serializer.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Cached/Serializer/item_deserializer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Cached/Serializer/prepare_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Cached/cdesc-Cached.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Cached/representable_mapper-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Cached/update%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/ClassInclusions/cdesc-ClassInclusions.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/ClassInclusions/included-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/ClassInclusions/inherited-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/ClassMethods/inherit_module%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/ClassMethods/prepare-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Cloneable/Hash/Clone/cdesc-Clone.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Cloneable/Hash/Clone/clone-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Cloneable/Hash/Clone/clone_value-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Cloneable/Hash/cdesc-Hash.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Cloneable/cdesc-Cloneable.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Coercion/ClassMethods/build_definition-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Coercion/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Coercion/Coercer/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Coercion/Coercer/cdesc-Coercer.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Coercion/Coercer/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Coercion/cdesc-Coercion.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Coercion/included-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Config/Definitions/add-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Config/Definitions/cdesc-Definitions.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Config/Definitions/definition_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Config/Definitions/get-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Config/Definitions/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Config/Definitions/remove-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Config/cdesc-Config.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Config/features-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Config/infer_name_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Config/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Config/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Config/wrap%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Config/wrap_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Debug/Binding/cdesc-Binding.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Debug/Binding/evaluate_option-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Debug/Binding/populator-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Debug/Binding/read-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Debug/Binding/serializer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Debug/Deserializer/cdesc-Deserializer.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Debug/Deserializer/create_object-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Debug/Mapper/cdesc-Mapper.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Debug/Mapper/compile_fragment-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Debug/Mapper/uncompile_fragment-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Debug/Populator/cdesc-Populator.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Debug/Populator/deserialize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Debug/Populator/deserializer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Debug/Representable/cdesc-Representable.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Debug/Representable/create_representation_with-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Debug/Representable/representable_mapper-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Debug/Representable/update_properties_from-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Debug/Serializer/cdesc-Serializer.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Debug/Serializer/marshal-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Debug/cdesc-Debug.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Debug/extended-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Declarative/build_config-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Declarative/build_definition-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Declarative/build_inline-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Declarative/cdesc-Declarative.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Declarative/collection-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Declarative/hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Declarative/inline_representer_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Declarative/nested-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Declarative/property-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Declarative/representable_attrs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Declarative/representation_wrap%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Decorator/InheritModule/cdesc-InheritModule.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Decorator/InheritModule/inherit_module%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Decorator/InheritModule/manifest%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Decorator/build_inline-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Decorator/cdesc-Decorator.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Decorator/clone-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Decorator/decorated-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Decorator/default_inline_class-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Decorator/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Decorator/prepare-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Decorator/represented-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Definition/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Definition/array%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Definition/cdesc-Definition.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Definition/clone-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Definition/create_binding-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Definition/delete%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Definition/dynamic_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Definition/getter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Definition/handle_as%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Definition/handle_extend%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Definition/has_default%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Definition/hash%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Definition/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Definition/merge%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Definition/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Definition/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Definition/representable%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Definition/representer_module-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Definition/runtime_options%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Definition/setter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Definition/setup%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Definition/typed%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/DeserializeError/cdesc-DeserializeError.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Deserializer/Collection/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Deserializer/Collection/cdesc-Collection.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Deserializer/Collection/deserialize%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Deserializer/Collection/item_deserializer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Deserializer/Hash/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Deserializer/Hash/cdesc-Hash.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Deserializer/Prepare/cdesc-Prepare.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Deserializer/Prepare/prepare%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Deserializer/Prepare/prepare-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Deserializer/Prepare/prepare_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Deserializer/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Deserializer/cdesc-Deserializer.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Deserializer/class_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Deserializer/class_from-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Deserializer/create_object-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Deserializer/demarshal-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Deserializer/deserialize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Deserializer/instance_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Deserializer/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Feature/cdesc-Feature.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Feature/feature-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Feature/register_feature-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/ForCollection/cdesc-ForCollection.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/ForCollection/collection_representer%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/ForCollection/collection_representer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/ForCollection/for_collection-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Hash/AllowSymbols/cdesc-AllowSymbols.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Hash/AllowSymbols/filter_wrap_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Hash/AllowSymbols/update_properties_from-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Hash/Binding/Collection/cdesc-Collection.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Hash/Binding/Hash/cdesc-Hash.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Hash/Binding/build_for-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Hash/Binding/cdesc-Binding.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Hash/Binding/deserialize_method-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Hash/Binding/read-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Hash/Binding/serialize_method-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Hash/Binding/write-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Hash/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Hash/ClassMethods/collection_representer_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Hash/Collection/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Hash/Collection/ClassMethods/items-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Hash/Collection/cdesc-Collection.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Hash/Collection/create_representation_with-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Hash/Collection/included-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Hash/Collection/update_properties_from-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Hash/Conversion/cdesc-Conversion.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Hash/Conversion/stringify_keys-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Hash/cdesc-Hash.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Hash/filter_wrap-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Hash/filter_wrap_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Hash/from_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Hash/included-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Hash/to_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/HashMethods/cdesc-HashMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/HashMethods/create_representation_with-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/HashMethods/filter_keys_for%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/HashMethods/update_properties_from-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Inheritable/Array/cdesc-Array.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Inheritable/Array/inherit%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Inheritable/Hash/InstanceMethods/cdesc-InstanceMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Inheritable/Hash/InstanceMethods/clone-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Inheritable/Hash/InstanceMethods/clone_value-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Inheritable/Hash/InstanceMethods/inherit%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Inheritable/Hash/cdesc-Hash.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Inheritable/cdesc-Inheritable.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/JSON/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/JSON/ClassMethods/collection_representer_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/JSON/Collection/cdesc-Collection.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/JSON/Collection/included-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/JSON/Hash/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/JSON/Hash/ClassMethods/values-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/JSON/Hash/cdesc-Hash.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/JSON/Hash/included-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/JSON/cdesc-JSON.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/JSON/from_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/JSON/included-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/JSON/to_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Mapper/Methods/bindings-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Mapper/Methods/cdesc-Methods.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Mapper/Methods/compile_fragment-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Mapper/Methods/deserialize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Mapper/Methods/deserialize_property-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Mapper/Methods/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Mapper/Methods/serialize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Mapper/Methods/serialize_property-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Mapper/Methods/skip_conditional_property%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Mapper/Methods/skip_excluded_property%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Mapper/Methods/skip_property%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Mapper/Methods/skip_protected_property-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Mapper/Methods/uncompile_fragment-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Mapper/cdesc-Mapper.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/ModuleExtensions/cdesc-ModuleExtensions.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/ModuleExtensions/extended-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Object/Binding/Collection/cdesc-Collection.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Object/Binding/build_for-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Object/Binding/cdesc-Binding.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Object/Binding/deserialize_method-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Object/Binding/read-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Object/Binding/serialize_method-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Object/Binding/write-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Object/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Object/ClassMethods/collection_representer_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Object/cdesc-Object.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Object/from_object-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Object/included-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Object/to_object-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/ParseStrategy/FindOrInstantiate/apply%21-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/ParseStrategy/FindOrInstantiate/cdesc-FindOrInstantiate.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/ParseStrategy/Proc/apply%21-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/ParseStrategy/Proc/cdesc-Proc.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/ParseStrategy/Sync/apply%21-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/ParseStrategy/Sync/cdesc-Sync.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/ParseStrategy/apply%21-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/ParseStrategy/cdesc-ParseStrategy.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/ParseStrategy/parse_strategies-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Pipeline/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Pipeline/cdesc-Pipeline.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Populator/Collection/cdesc-Collection.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Populator/Collection/deserialize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Populator/Hash/cdesc-Hash.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Populator/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Populator/cdesc-Populator.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Populator/deserialize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Populator/deserializer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Populator/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Represent/cdesc-Represent.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Represent/represent-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Serializer/Collection/cdesc-Collection.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Serializer/Collection/serialize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Serializer/Hash/cdesc-Hash.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Serializer/Hash/serialize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Serializer/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Serializer/cdesc-Serializer.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Serializer/marshal-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Serializer/serialize%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/Serializer/serialize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/AttributeHash/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/AttributeHash/ClassMethods/values-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/AttributeHash/cdesc-AttributeHash.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/AttributeHash/included-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/Binding/Attribute/cdesc-Attribute.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/Binding/Attribute/read-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/Binding/Attribute/serialize_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/Binding/Attribute/write-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/Binding/AttributeHash/cdesc-AttributeHash.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/Binding/AttributeHash/deserialize_from-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/Binding/AttributeHash/write-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/Binding/Collection/cdesc-Collection.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/Binding/Collection/deserialize_from-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/Binding/Collection/serialize_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/Binding/Collection/set_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/Binding/Content/cdesc-Content.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/Binding/Content/read-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/Binding/Content/serialize_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/Binding/Content/write-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/Binding/Hash/cdesc-Hash.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/Binding/Hash/deserialize_from-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/Binding/Hash/serialize_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/Binding/build_for-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/Binding/cdesc-Binding.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/Binding/content_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/Binding/deserialize_from-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/Binding/deserialize_method-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/Binding/find_nodes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/Binding/node_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/Binding/read-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/Binding/serialize_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/Binding/serialize_method-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/Binding/serialize_node-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/Binding/write-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/Binding/xpath-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/ClassMethods/collection_representer_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/ClassMethods/remove_namespaces%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/Collection/Methods/cdesc-Methods.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/Collection/Methods/update_properties_from-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/Collection/cdesc-Collection.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/Collection/included-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/Hash/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/Hash/ClassMethods/values-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/Hash/cdesc-Hash.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/Hash/included-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/cdesc-XML.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/from_node-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/from_xml-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/included-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/parse_xml-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/remove_namespaces%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/to_node-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/XML/to_xml-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/YAML/Binding/Collection/cdesc-Collection.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/YAML/Binding/Collection/node_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/YAML/Binding/build_for-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/YAML/Binding/cdesc-Binding.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/YAML/Binding/deserialize_method-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/YAML/Binding/node_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/YAML/Binding/serialize_method-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/YAML/Binding/write-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/YAML/Binding/write_scalar-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/YAML/cdesc-YAML.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/YAML/from_yaml-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/YAML/included-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/YAML/to_ast-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/YAML/to_yaml-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/cdesc-Representable.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/create_representation_with-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/included-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/normalize_options%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/representable_attrs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/representable_binding_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/representable_bindings_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/representable_mapper-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/representation_wrap-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/represented-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/Representable/update_properties_from-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/representable-2.2.3/ri/lib/representable/page-TODO_getting_serious.ri
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/.travis.yml
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/CHANGES.md
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/README.md
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/TODO
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/lib/representable.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/lib/representable/TODO.getting_serious
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/lib/representable/apply.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/lib/representable/autoload.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/lib/representable/binding.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/lib/representable/cached.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/lib/representable/coercion.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/lib/representable/config.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/lib/representable/debug.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/lib/representable/declarative.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/lib/representable/decorator.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/lib/representable/definition.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/lib/representable/deserializer.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/lib/representable/for_collection.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/lib/representable/hash.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/lib/representable/hash/allow_symbols.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/lib/representable/hash/binding.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/lib/representable/hash/collection.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/lib/representable/hash_methods.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/lib/representable/inheritable.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/lib/representable/json.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/lib/representable/json/collection.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/lib/representable/json/hash.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/lib/representable/mapper.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/lib/representable/object.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/lib/representable/object/binding.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/lib/representable/parse_strategies.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/lib/representable/pipeline.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/lib/representable/populator.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/lib/representable/represent.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/lib/representable/serializer.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/lib/representable/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/lib/representable/xml.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/lib/representable/xml/binding.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/lib/representable/xml/collection.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/lib/representable/xml/hash.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/lib/representable/yaml.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/lib/representable/yaml/binding.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/representable.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/as_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/benchmarking.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/binding_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/cached_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/class_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/coercion_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/config/inherit_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/config_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/decorator_scope_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/decorator_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/definition_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/example.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/examples/object.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/exec_context_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/features_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/filter_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/for_collection_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/generic_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/getter_setter_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/hash_bindings_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/hash_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/if_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/inherit_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/inheritable_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/inline_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/instance_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/is_representable_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/json_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/lonely_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/mongoid_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/nested_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/object_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/parse_strategy_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/pass_options_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/prepare_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/reader_writer_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/realistic_benchmark.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/represent_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/representable_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/schema_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/serialize_deserialize_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/skip_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/stringify_hash_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/test_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/test_helper_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/wrap_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/xml_bindings_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/xml_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/representable-2.2.3/test/yaml_test.rb
/usr/lib64/ruby/gems/2.2.0/specifications/representable-2.2.3.gemspec
