#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-representable
Version  : 2.4.1
Release  : 4
URL      : https://rubygems.org/downloads/representable-2.4.1.gem
Source0  : https://rubygems.org/downloads/representable-2.4.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-bundler
BuildRequires : rubygem-json
BuildRequires : rubygem-minitest
BuildRequires : rubygem-mongoid
BuildRequires : rubygem-multi_json
BuildRequires : rubygem-nokogiri
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-ruby-prof
BuildRequires : rubygem-test_xml
BuildRequires : rubygem-uber
BuildRequires : rubygem-virtus

%description
# Representable
Representable maps Ruby objects to documents and back.
[![Gitter Chat](https://badges.gitter.im/trailblazer/chat.svg)](https://gitter.im/trailblazer/chat)
[![Build
Status](https://travis-ci.org/apotonick/representable.svg)](https://travis-ci.org/apotonick/representable)
[![Gem Version](https://badge.fury.io/rb/representable.svg)](http://badge.fury.io/rb/representable)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n representable-2.4.1
gem spec %{SOURCE0} -l --ruby > rubygem-representable.gemspec

%build
gem build rubygem-representable.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
representable-2.4.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/representable-2.4.1.gem
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/CHANGES.md
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/README.md
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/TODO
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/lib/representable.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/lib/representable/TODO.getting_serious
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/lib/representable/autoload.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/lib/representable/binding.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/lib/representable/cached.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/lib/representable/coercion.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/lib/representable/config.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/lib/representable/debug.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/lib/representable/declarative.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/lib/representable/decorator.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/lib/representable/definition.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/lib/representable/deprecations.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/lib/representable/deserializer.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/lib/representable/for_collection.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/lib/representable/hash.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/lib/representable/hash/allow_symbols.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/lib/representable/hash/binding.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/lib/representable/hash/collection.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/lib/representable/hash_methods.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/lib/representable/insert.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/lib/representable/json.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/lib/representable/json/collection.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/lib/representable/json/hash.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/lib/representable/object.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/lib/representable/object/binding.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/lib/representable/parse_strategies.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/lib/representable/pipeline.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/lib/representable/pipeline_factories.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/lib/representable/represent.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/lib/representable/serializer.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/lib/representable/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/lib/representable/xml.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/lib/representable/xml/binding.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/lib/representable/xml/collection.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/lib/representable/xml/hash.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/lib/representable/yaml.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/lib/representable/yaml/binding.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/representable.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/as_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/benchmarking.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/binding_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/blaaaaaaaa_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/cached_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/class_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/coercion_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/config/inherit_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/config_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/decorator_scope_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/decorator_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/default_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/defaults_options_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/definition_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/example.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/examples/object.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/exec_context_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/features_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/filter_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/for_collection_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/generic_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/getter_setter_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/hash_bindings_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/hash_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/heritage_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/if_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/include_exclude_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/inherit_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/inline_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/instance_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/is_representable_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/json_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/lonely_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/mongoid_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/nested_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/object_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/parse_pipeline_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/parse_strategy_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/pass_options_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/pipeline_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/populator_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/prepare_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/private_options_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/reader_writer_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/realistic_benchmark.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/render_nil_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/represent_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/representable_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/schema_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/serialize_deserialize_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/skip_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/stringify_hash_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/test_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/test_helper_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/uncategorized_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/user_options_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/wrap_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/xml_bindings_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/xml_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test-with-deprecations/yaml_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/as_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/benchmarking.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/binding_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/cached_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/class_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/coercion_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/config/inherit_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/config_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/decorator_scope_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/decorator_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/default_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/defaults_options_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/definition_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/example.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/examples/object.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/exec_context_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/features_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/filter_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/for_collection_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/generic_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/getter_setter_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/hash_bindings_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/hash_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/heritage_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/if_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/include_exclude_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/inherit_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/inline_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/instance_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/is_representable_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/json_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/lonely_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/mongoid_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/nested_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/object_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/parse_pipeline_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/parse_strategy_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/pipeline_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/populator_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/prepare_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/private_options_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/reader_writer_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/realistic_benchmark.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/render_nil_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/represent_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/representable_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/schema_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/serialize_deserialize_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/skip_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/stringify_hash_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/test_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/test_helper_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/uncategorized_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/user_options_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/wrap_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/xml_bindings_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/xml_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/representable-2.4.1/test/yaml_test.rb
/usr/lib64/ruby/gems/2.3.0/specifications/representable-2.4.1.gemspec
